
simple_server: simple_server.c
	gcc -o simple_server simple_server.c
	
simple_client: simple_client.c
	gcc -o simple_client simple_client.c

sock_test: sock_test.c
	gcc -o sock_test sock_test.c

show_ip: show_ip.c
	gcc -o show_ip show_ip.c

clean:
	rm -f *.o sock_test show_ip simple_server simple_client

